Interface dev
IncPlusPlus/beacon-frontend pull request #2
Opened 2022-02-18 16:27 UTC by Sciman101

Began developing the basic UI. Uses vanilla react, for now

2022-02-19 22:48 UTC, IncPlusPlus requested changes
This is a great start. Myself and the build script have two nitpicks and then this is good to go.

2022-02-19 22:48 UTC, IncPlusPlus commented on src/components/TowerList.js
> +            towers.push(<li className={'towerIcon' + (tower.id == this.props.selected ? ' selected' : '')}
```suggestion
            towers.push(<li className={'towerIcon' + (tower.id === this.props.selected ? ' selected' : '')}
```

2022-02-19 22:48 UTC, IncPlusPlus commented on src/components/ChannelList.js
> +            channels.push(<li  className={'channelIcon' + (channel.id == this.props.selected ? ' selected' : '')}
```suggestion
            channels.push(<li  className={'channelIcon' + (channel.id === this.props.selected ? ' selected' : '')} 
```

2022-02-19 22:55 UTC, IncPlusPlus commented on package-lock.json
> -  "lockfileVersion": 2,
I just noticed this after I finished my review. You seem to be on an older version of NodeJS (and therefore NPM). You can check with `npm --version` and `node --version`. Using an older version of the lockfile isn't really ideal so please update your installation. I recommend installing the latest _LTS_ version of NodeJS from [here](https://nodejs.org/en/).

2022-02-19 22:57 UTC, IncPlusPlus commented on package-lock.json
> -  "lockfileVersion": 2,
I'm not sure why it says that this change request comment is outdated. Ignore that little marker until the file has actually been changed.

2022-02-19 23:31 UTC, IncPlusPlus requested changes
The package-lock.json still seems to be the old format. Did you commit and push after you re-ran `npm install`?

2022-02-20 00:12 UTC, IncPlusPlus approved these changes
LGTM!

2022-02-23 18:12 UTC, grabockatATWIT reviewed
i think the css pages looks good. i made a couple of comments but it'll still work w/o my suggestions

2022-02-23 18:12 UTC, grabockatatwit commented on src/index.css
> +  border-radius: 16px 0 0 16px;
to simplify the line you can do:
border-radius: 16px 0px 16px;

2022-02-23 18:12 UTC, grabockatATWIT commented on src/index.css
> +  border-radius: 16px 0 0 16px;
to simplify the line you can do:
border-radius: 16px 0px 16px;

2022-02-23 18:12 UTC, grabockatATWIT commented on src/index.css
> +  overflow: scroll;
maybe instead of "scroll", make it "auto" so that it only allows scrolling if needed

2022-03-02 16:04 UTC, merged